src/components/button/button-group.vue
src/styles/components/button.less
src/styles/mixins/button.less
test/routers/button.vue

实现Button Group垂直排列
* 添加API vertical，type boolean
* 添加tests

implemented vertical align mode of button

---

src/components/table/cell.vue
src/styles/components/table.less
test/routers/table.vue

Added ellipsis property to table column

---

src/components/table/table-body.vue
src/components/table/table.vue
test/routers/table.vue

fixed #140 
Usage
```
@on-click=""
@on-dblclick=""
```

Added click and dblclick events to table

---

src/components/select/select.vue
test/routers/select.vue

fixed #178

---

src/components/table/table.vue
test/routers/table.vue

Fade table body when there is no data

---

src/components/table/table.vue
test/routers/table.vue

Changed parameters of sort method of Table

---

src/components/carousel/carousel.vue
test/routers/carousel.vue

reset autoplay timer after trigger

---

src/components/modal/modal.vue
test/routers/more.vue

added scrolling property to toggle CSS for creating or hiding scrollbars

---

src/components/carousel/carousel.vue
src/components/notice/index.js
src/styles/animation/move.less
test/app.vue
test/main.js
test/routers/notice.vue

IE<=11 do not support toString.

---

src/components/input-number/input-number.vue

changed regular expression to fit exactly one zero

---

src/components/modal/confirm.js
src/components/slider/slider.vue
src/components/tooltip/tooltip.vue
test/routers/more.vue
test/routers/slider.vue

added show-tip to slider and added always to tooltip

---

src/components/cascader/cascader.vue
test/routers/cascader.vue

fix bug: cascader still can be opened if set to disabled

---

build/webpack.dev.config.js
package.json
src/components/steps/step.vue
src/components/steps/steps.vue
src/index.js
test/app.vue
test/main.js
test/routers/steps.vue

1. support Steps
2. fixed npm run dev error with  cann't find module vue-template-compiler
3. update test demo style

support Steps

---

build/webpack.dev.config.js
package.json
src/components/steps/step.vue
src/components/steps/steps.vue
src/components/timeline/timeline-item.vue
src/index.js
test/app.vue
test/main.js
test/routers/steps.vue
test/routers/timeline.vue

1. contains the branch feature-steps
2. add Timeline demo

Support Timeline

---

README.md
examples/app.vue
examples/main.js
examples/routers/back-top.vue
src/components/back-top/back-top.vue
src/index.js

2.0 backtop

---

examples/routers/tabs.vue
src/components/tabs/tabs.vue
src/styles/components/tabs.less

tabs组件导航区添加右侧slot功能及修改例子文件

---

src/locale/lang/tr-TR

Added Turkish

---

examples/routers/message.vue
src/components/base/notification/index.js
src/components/base/notification/notification.vue

Bugfix on Message's $destroy method. It won't work before.

bugfix on Message

---

examples/routers/steps.vue
src/components/steps/step.vue

步骤组件只有个描述信息很多时候不能满足业务需要，因此加上了slot支持

给Step组件增加slot支持

---

examples/routers/table.vue
src/components/table/table.vue

filterRemote 和 filterMethod 同时支持，优先filterRemote方法

添加filterRemote方法，支持用户远程筛选数据

---

examples/routers/tree.vue
src/components/tree/node.vue
src/components/tree/tree.vue

当点击展开/收回按钮时，会触发 `on-toggle-expand` 事件，返回当前节点对象。

new feature: @on-toggle-expand on Tree

---

examples/routers/input-number.vue
examples/routers/input.vue
src/components/input-number/input-number.vue
src/components/input/input.vue

Input 和input-number 组件增加autofocus属性

Input 组件增加autofocus属性

---

README.md

Change gitter badge style to flat-square.

Change gitter badge style

---

src/components/form/form.vue

修复form表单在只有一个input情况下,按下enter触发submit事件.
http://www.alanflavell.org.uk/www/formquestion.html

fix form default submit behavior.

---

src/locale/lang/ru-RU.js

Add Russ lang

---

examples/routers/transfer.vue
src/components/transfer/transfer.vue

Bugfix: Transfer will throw error during rendering if items in target-list cannot be found in source list. The error will cause render failure.

bugfix on transfer

---

src/components/modal/modal.vue

增加modal隐藏时的时间
部分需求会在modal关闭时重置modal数据,此时会存在ui闪动的情况.
[https://jsfiddle.net/marvinwilliam/1rthkx4a/3/embedded/result,js,html/](https://jsfiddle.net/marvinwilliam/1rthkx4a/3/embedded/result,js,html/)

add modal hidden event

---

src/styles/mixins/select.less

fixed Select option with selected push one line in the firefox

---

src/styles/components/upload.less

fixed #1258

---

examples/routers/table.vue
src/components/table/table.vue

Add an event @on-select-cancel to Table

---

src/components/page/page.vue

fix bug that it cannot input number in Page by right side keyboard

---

src/components/card/card.vue
src/components/message/index.js

assign names to Card and Message

---

examples/routers/progress.vue
src/components/progress/progress.vue
src/styles/components/progress.less

Add vertical progressbar

---

examples/routers/tabs.vue
src/styles/components/tabs.less

Restrict no-animation config only affect one layer of children

---

src/locale/lang/vi-VN.js

I realize that there is missing locale for VN language. I hope this file could help. 😄

Add locale for VN language

---

examples/routers/input-number.vue
src/components/input-number/input-number.vue

Add watchers for min and max in inputNumber

---

examples/routers/date.vue
src/components/date-picker/picker.vue

Return array of format string when type is datetimerange

---

examples/routers/tree.vue
src/components/tree/tree.vue

Skip checking children if it was empty

---

examples/routers/checkbox.vue
examples/routers/radio.vue
src/components/checkbox/checkbox.vue
src/components/radio/radio.vue

Support trueValue and falseValue

---

examples/routers/page.vue
src/components/page/page.vue

be able to use `:current.sync` in Page

Emit current update when page changed

---

src/components/base/popper.js

#1587 
add on-popper-show event in Poptip events

add on-popper-show event in Poptip events

---

test/unit/specs/date-picker.spec.js

This is just a unit test to check the DatePicker renders the correct month.

add basic DatePicker test

---

src/components/rate/rate.vue

Fix rating when init value is decimal

---

src/components/table/table.vue

Added `0` to reduce method without initial value
fixes #1736

Add counter start to reduce

---

src/components/input/input.vue

By the browser automatically filled in Input
model is ''

Input increase autocomplete

---

src/components/slider/slider.vue

https://github.com/iview/iview/issues/1354

修复 Slider 滑动按钮单击时数值跳动 issue

---

package-lock.json
package.json

Sinon was updated to major `”sinon": "^3.2.1”,`
> warning "karma-sinon-chai@1.3.2" has incorrect peer dependency "sinon@^2.1.0".

Update Sinon to major v.3 because of peer dependencies

---

src/components/date-picker/picker/date-picker.js
test/unit/specs/date-picker.spec.js

Propagate type changes to panel

---

src/styles/components/message.less

解决多个 Message 重叠 (如果是个 feature 就忽略我)

---

src/components/date-picker/base/date-table.vue
src/locale/lang/de-DE.js
src/locale/lang/en-US.js
src/locale/lang/es-ES.js
src/locale/lang/fr-FR.js
src/locale/lang/id-ID.js
src/locale/lang/ja-JP.js
src/locale/lang/ko-KR.js
src/locale/lang/pt-BR.js
src/locale/lang/pt-PT.js
src/locale/lang/ru-RU.js
src/locale/lang/sv-SE.js
src/locale/lang/tr-TR.js
src/locale/lang/vi-VN.js
src/locale/lang/zh-CN.js
src/locale/lang/zh-TW.js

New feature: week can start on monday/sunday depending on Locale settings (closes https://github.com/iview/iview/issues/1809)

Add week start (locale setting)

---

src/components/date-picker/panel/date.vue

Refactor to reduce code length and repetition

refactor and reduce code logic

---

build/build-style.js
build/locale.js
build/webpack.base.config.js
build/webpack.dev.config.js
build/webpack.dist.dev.config.js
build/webpack.dist.locale.config.js
build/webpack.dist.prod.config.js
build/webpack.test.config.js
package-lock.json
package.json

This PR is to use good ideas from #1281 that has merge-conflicts since we already use Webpack 3.
closes #1281

Re-use pr1281

---

.eslintrc.json
package-lock.json
package.json
src/components/scroll/index.js
src/components/scroll/loading-component.vue
src/components/scroll/scroll.vue
src/index.js
src/styles/components/index.less
src/styles/components/scroll.less

New feature: `<Scroll>`
The ideia is to have a "infinite scroll" or "loader" functionality similar to [ElementFE's](https://github.com/ElemeFE/vue-infinite-scroll) or [PeachScript's](https://github.com/PeachScript/vue-infinite-loading).
Features:
- suport loading on top
- suppor loading on bottom
- triggers load on mouse wheel & touch "drag"
- allows loading text (optional) 
**Demo** (very basic): https://jsfiddle.net/Sergio_fiddle/x9vpsjo5/

New feature: Scroll component

---

src/utils/assist.js

Remove unused code
Small refactor

remove unused code, small refactor

---

src/components/date-picker/picker.vue
test/unit/specs/date-picker.spec.js

fixes https://github.com/iview/iview/issues/2119

correct behaviour when initialising date-picker with a empty string

---

src/components/scroll/scroll.vue

add missing event in callback

---

examples/routers/table.vue
src/components/table/table.vue
src/utils/csv.js
test/unit/specs/assets/table/csvData.js
test/unit/specs/table.spec.js

New features:
- added`callback`option so we can get CSV data in case we do not want to download (needed for specs and asked for in https://github.com/iview/iview/issues/1803)
- added options:
- `quoted` for cases when we have line breaks in content
- `separator` for cases when we have commas in content
Also: added unit tests
fixes https://github.com/iview/iview/issues/2109
fixes https://github.com/iview/iview/issues/1803

Improve export to CSV functionality

---

examples/routers/tabs.vue
src/components/tabs/tabs.vue
src/styles/components/tabs.less

Tabs add scroll

---

src/styles/components/tag.less

update Tag style for check

---

src/components/date-picker/util.js
test/unit/specs/assets/locale-expects.js
test/unit/specs/date-picker.spec.js

Fixes #2163
(this was a bug left from my refactoring in #2097)

Correct month calculation and add specs for date-picker labels

---

src/components/date-picker/picker.vue
test/unit/specs/date-picker.spec.js
test/unit/util.js

format string dates in daterange also

---

README.md

This PR changes some of the English sentences in the `README.md` to sound more natural. I have tried to keep the structure as close as possible to the original. If anything sounds confusing, please reply below.
这个PR改变了`README.md`中的一些英文句子，使其听起来更自然。 我试图保持结构尽可能接近原来。 如有任何疑问，请在下面回覆。

Fix some English grammar in README

---

examples/routers/carousel.vue
src/components/carousel/carousel-item.vue
src/components/carousel/carousel.vue
src/styles/components/carousel.less

Update carousel component: add loop and radiusDot property
#	package.json
#	src/components/date-picker/picker.vue
#	src/components/select/select.vue

Update carousel component: add loop and radiusDot property

---

src/components/table/table.vue

解决tabs切换时,tab中的table调试时控制台报$el undefined的问题

Update table.vue  解决tabs切换时,tab中的table调试时控制台报$el undefined的问题

---

src/components/select/option.vue
test/unit/specs/select.spec.js

correct input value in filterable mode

---

src/components/input-number/input-number.vue

prevent firing change when typing numbers < min

---

examples/routers/form.vue
src/styles/components/color-picker.less
src/styles/components/input.less

- Optimize small colorpicker icon position
- Fix small input & date & time icon position incorrectly

fixed: #2219 & ColorPicker icon position

---

src/components/form/form.vue

feat(form) : support promise for validate method #1857

---

src/components/tabs/tabs.vue

Tests passed with `npm test`.
Description of this issue and the fix can be found [here](https://github.com/iview/iview/issues/1846#issuecomment-340310024).

fix issue #1846

---

src/locale/lang/uk-UA.js

add uk_UA locale

---

test/unit/specs/date-picker.spec.js

Had a bad config in my last test (https://github.com/iview/iview/pull/2361), fixed now.

fix date picker callback test

---

src/index.js

reorganize and DRY components list

reorganize and DRY components list

---

src/locale/lang/es-ES.js

Change of name of long weekdays to short weekdays name, for use in datepicker

Long weekdays name to short weekdays name

---

src/locale/lang/it-IT.js

Italian locale file

---

package-lock.json
src/components/breadcrumb-item/index.js
src/components/button-group/index.js
src/components/carousel-item/index.js
src/components/checkbox-group/index.js
src/components/col/index.js
src/components/dropdown-item/index.js
src/components/dropdown-menu/index.js
src/components/dropdown/dropdown-menu.vue
src/components/form-item/index.js
src/components/i18n/index.js
src/components/locale/index.js
src/components/menu-group/index.js
src/components/menu-item/index.js
src/components/option-group/index.js
src/components/option/index.js
src/components/options/index.js
src/components/pane/index.js
src/components/panel/index.js
src/components/radio-group/index.js
src/components/row/index.js
src/components/select/index.js
src/components/step/index.js
src/components/sub-menu/index.js
src/components/tab-pane/index.js
src/components/timeline-item/index.js

perfect demand import

---

src/components/tabs/tabs.vue

解决isInsideHiddenElement函数下parentNode.style对象的display报错的bug

---

src/locale/lang/th-TH.js

Add th-TH.js

---

src/components/date-picker/panel/time-range.vue

Fix: Missing steps attribute in time range.

---

examples/routers/modal.vue
src/components/modal/confirm.js

add closable props for $Modal https://github.com/iview/iview/issues/2362

add closable props for $Modal https://github.com/iview/iview/issues/2362

---

examples/app.vue
examples/main.js
examples/routers/layout.vue
src/components/content/index.js
src/components/footer/index.js
src/components/header/index.js
src/components/layout/content.vue
src/components/layout/footer.vue
src/components/layout/header.vue
src/components/layout/index.js
src/components/layout/layout.vue
src/components/layout/sider.vue
src/components/sider/index.js
src/index.js
src/styles/components/index.less
src/styles/components/layout.less
src/styles/custom.less
src/utils/assist.js

add layout component with header, content, sider and footer

 add layout component with header, content, sider and footer

---

examples/routers/tag.vue
src/components/tag/tag.vue
src/styles/components/tag.less

close #2406

---

examples/routers/message.vue
examples/routers/notice.vue
src/components/base/notification/index.js
src/components/base/notification/notice.vue
src/components/base/notification/notification.vue
src/components/message/index.js
src/components/notice/index.js
src/styles/components/notice.less

make Message and Notice support render

make Message and Notice support render

---

examples/routers/message.vue
examples/routers/notice.vue
examples/routers/tag.vue
package.json
src/components/base/notification/notice.vue
src/components/base/notification/notification.vue
src/components/notice/index.js
src/components/tag/tag.vue

udpate notice

---

examples/routers/tag.vue
src/components/tag/tag.vue

fixed the bug about backgroundcolor when tag is checked

fixed the bug about backgroundcolor when tag is checked

---

examples/routers/notice.vue
src/components/notice/index.js

fixed bug of notice when has render and title bug no desc

---

src/locale/lang/ro-RO

Romanian language

---

src/components/select/dropdown.vue

fix: https://github.com/iview/iview/issues/2780#issuecomment-356486974

dropdown component in fast switch display hidden times error

---

src/components/button/button.vue
src/styles/components/button.less
src/styles/mixins/button.less

Gives visual feedback, like mouse hover, when button is focused via tab navigation.

Feature: Button tab navigation

---

package.json
src/index.js
yarn.lock

Re: https://github.com/iview/iview/pull/2839#issuecomment-358236307

Remove core-js as no longer required

---

.travis.yml

This is a fix for a regression in Travis or Chrome headless.
Used the fix suggested in https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348198699 and build went OK.

Fix travis regression

---

src/components/radio/radio.vue
src/styles/components/radio.less

Radio: Tabindex WIP

---

src/components/checkbox/checkbox.vue
src/styles/mixins/checkbox.less

Checkbox: Tabindex WIP

---

src/components/checkbox/checkbox.vue

Checkbox tabindex

---

examples/routers/checkbox.vue
src/components/checkbox/checkbox.vue

 Don't tab to disable checkboxes

---

examples/routers/checkbox.vue
src/components/checkbox/checkbox-group.vue
src/components/checkbox/checkbox.vue
src/styles/mixins/checkbox.less

Checkbox w3c

---

src/components/select/option.vue

解决select-item引起的大量内存泄漏的bug

---

src/components/slider/slider.vue

 Fix slider for min/max values greater than 100

---

src/components/slider/slider.vue

Fixes https://github.com/iview/iview/issues/2975
(this PR fixes a regression I introduced in 2.9.1)

Emit change on pointer up also

---

src/components/menu/menu.vue

Revert "updateOpened时判断accordion"

---

src/components/table/table.vue

Performance Improvements when Table Select

---

src/components/switch/switch.vue

Switch: Add keyboard control

---

src/components/slider/slider.vue

normalise public (export) value to number of step decimal cases

---

src/components/date-picker/picker.vue
src/components/date-picker/util.js
test/unit/specs/date-picker.spec.js
test/unit/util.js

Pass correct arguments to `on-change` callback

---

src/components/slider/slider.vue
src/styles/components/slider.less

Slider: Keyboard control like native

---

package-lock.json
package.json
yarn.lock

https://github.com/benjamingr/RegExp.escape
This just installs the library for use with components in future, i.e. select rework

Use RegExp.escape proposal library for user input

---

examples/routers/select.vue

Add select examples from the docs for rework of the select component

---

src/utils/kbEventKeys.js

Keyboard event key constants

---

src/utils/assist.js

Kebab join utility for composing reusable constants from smaller parts

---

src/utils/eventNames.js

This is not all of them, just those found during the select rework

Common event name constants, used by $emit and $on - DRY

---

src/utils/enums.js

This is not all of them, just those found during the select rework.

Common enums used in the project -DRY

---

src/locale/lang/ro-RO.js

Fix: Missing file extension

---

src/components/date-picker/base/mixin.js

Prevent clicking in week number label

---

src/components/date-picker/picker.vue
test/unit/specs/date-picker.spec.js

Pass Strings to @on-change and Dates to v-model

---

src/components/date-picker/panel/Date/date-panel-mixin.js
src/components/date-picker/panel/Date/date-range.vue
src/components/date-picker/panel/Date/date.vue
src/components/date-picker/picker.vue

A use case would be:
<date-picker type="datetime" :time-picker-options="{steps: [1, 10, 10]}"></date-picker>

Allow DatePicker to receive TimePicker options

---

build/webpack.base.config.js
build/webpack.dev.config.js
build/webpack.dist.dev.config.js
build/webpack.dist.locale.config.js
build/webpack.dist.prod.config.js
build/webpack.test.config.js

This enables sourcemap creation which greatly assists with debugging the library.
For some background reading https://www.google.se/search?q=javascript+sourcemaps&oq=javascript+source&aqs=chrome.0.69i59j69i57j69i60l2j0l2.4415j0j7&sourceid=chrome&ie=UTF-8

Enable creation of sourcemaps

---

examples/routers/cascader.vue
examples/routers/select.vue
package-lock.json
package.json
src/components/base/popper.js
src/components/cascader/cascader.vue
src/components/select/dropdown.vue

Select、Dropdown、DatePicker等浮层placement自适应

---

src/components/cascader/cascader.vue
src/components/date-picker/picker.vue
src/components/dropdown/dropdown.vue
src/components/select/dropdown.vue
src/components/select/select.vue
src/styles/animation/slide.less

解决dropdown弹出动画异常

---

examples/routers/input-number.vue
src/components/input-number/input-number.vue

InputNumber support null values

---

src/components/date-picker/picker.vue

Fix type passed when no value is given for timerange

---

src/components/date-picker/panel/Date/date-range.vue

Always apply same increment to not splited panels

---

examples/routers/table.vue
src/components/color-picker/color-picker.vue
src/components/table/mixin.js
src/components/table/table-head.vue
src/components/table/table.vue

1、解决表格设置高度，表头过长换行导致滚动条下面溢出
2、解决表格设置高度，滚动条没有显示导致表头右边溢出

fixed table scrollbar bug

---

examples/routers/table.vue
src/components/table/table.vue

Table fixed columns support mouse scroll

---

examples/routers/table.vue
src/components/table/mixin.js
src/components/table/table.vue
src/styles/components/table.less

fix table fixed right header

---

examples/routers/table.vue
src/components/table/mixin.js
src/components/table/table-body.vue
src/components/table/table-head.vue
src/components/table/table.vue
src/styles/components/table.less

fixed table scollbar

---

src/components/card/card.vue

Card组件增加title和icon属性，简化用户使用

---

src/components/select/dropdown.vue

fix select dropdown position

---

src/components/dropdown/dropdown-item.vue

采用 findComponentUpward 替代 this.$parent.$parent.$parent 获取 Dropdown 父节点组件

---

src/components/form/form-item.vue
src/components/form/form.vue

 采用inject方法，修正问题：当FormItem组件在slot里时，无法正确获取form组件

---

src/components/tree/node.vue
src/components/tree/tree.vue

为 Tree 组件添加新的属性`childrenKey`，使用户可以自定义`children`的键值。
```vue
<Tree :data="data" :children-key="userDefinedKey"></Tree>
```

Add new props 'childrenKey' to Tree component

---

src/components/date-picker/picker.vue
src/components/date-picker/util.js

Fix date parsing

---

src/components/date-picker/base/date-table.vue

compute calendar so we react on showWeekNumbers changes

---

src/components/date-picker/panel/Date/date.vue
src/components/date-picker/panel/Time/time.vue

Allow disableDate function to limit time-spinner numbers

---

src/components/date-picker/panel/Date/date-range.vue

Correct logic for side panel date

---

examples/routers/dropdown.vue
examples/routers/poptip.vue
src/components/base/popper.js
src/components/select/dropdown.vue

解决dropdown的placement设置部分样式为如right-start，弹出动画异常
解决popper的boundariesElement设置为body不会根据弹出的大小计算合适的位置，会导致有空间还溢出的bug

update popper animation

---

examples/routers/collapse.vue
src/components/collapse/collapse.vue

永远不会走到`self.accordion`的判断里，`self`指向的`window`，
且`activeKey`在`this.getActiveKey()`里已经处理过，一定返回数组，且`this.accordion`为真时只截取数组的第一个返回，所以可以删掉某些代码

delete: collapse组件不需要的代码

---

examples/routers/poptip.vue
src/components/base/popper.js

update poptip content change

---

src/directives/transfer-dom.js

resolve the transfer-dom.js not support ie9
in ie9 the "el.dataset" not support,so we should set condition is "el.dataset && el.dataset.transfer"

resolve the transfer-dom.js not support ie9

---

src/components/carousel/carousel.vue

This fixes issue #3426  
Button in carousel should set to type="button", 
to avoid unnecessary form submition.

Add button type in carousel

---

examples/routers/input-number.vue
src/components/input-number/input-number.vue

inputNumber组件添加placeholder属性

---

src/components/slider/slider.vue

Correct values passed to checkLimits method

---

examples/routers/rate.vue
src/components/rate/rate.vue

 rate组件添加allowClear属性，通过点击可以把当前评分清零

---

build/webpack.dist.locale.config.js
build/webpack.dist.prod.config.js
package-lock.json
package.json
src/components/select/functional-options.vue
src/components/select/option.vue
src/components/select/select-head.vue
src/components/select/select.vue
src/styles/components/select.less
test/unit/specs/select.spec.js

This PR is a refactor of the Select component to reduce complexity and code length. 
It uses the great work done by @Xotic750 and should solve the tab/keyboard navigation functionality related to https://github.com/iview/iview/issues/1647
Review welcome! If there are some things I forgot let me know.

Refactor select, fix tab/keyboard navigation

---

src/components/spin/spin.js

Hi, @icarusion   spread the pr.

fix: calling Spin.hide() continuously

---

src/components/auto-complete/auto-complete.vue
yarn.lock

feat: exposure `on-focus` and `on-blur` event in <AutoComplete>

---

src/components/notice/index.js

Lack of space causes style display errors

Class string error

---

examples/routers/select.vue
src/components/select/select-head.vue
src/components/select/select.vue

Add `on-clear` event to Select component so we can lysten to it from the outside.

more select improvements

---

src/locale/lang/es-ES.js

fix month 12th name: Deciembre -> Diciembre

fix month 12th name

---

examples/routers/date.vue
src/components/date-picker/base/confirm.vue
src/components/date-picker/base/date-table.vue
src/components/date-picker/base/mixin.js
src/components/date-picker/base/month-table.vue
src/components/date-picker/base/time-spinner.vue
src/components/date-picker/base/year-table.vue
src/components/date-picker/panel/Date/date-panel-mixin.js
src/components/date-picker/panel/Date/date-range.vue
src/components/date-picker/panel/Date/date.vue
src/components/date-picker/picker.vue
src/components/date-picker/picker/date-picker.js
src/components/date-picker/picker/time-picker.js
src/styles/components/date-picker.less
src/styles/components/time-picker.less
test/unit/specs/date-picker.spec.js
test/unit/specs/time-spinner.spec.js

Add keyboard navigation to DatePicker
(**Obs:** please review and give feedback about it before merging, we are still testing also but would be nice to have more feedback also)
related to #1647

Datepicker keyboard

---

examples/routers/color-picker.vue
src/components/color-picker/alpha.vue
src/components/color-picker/color-picker.vue
src/components/color-picker/handleEscapeMixin.js
src/components/color-picker/hsaMixin.js
src/components/color-picker/hue.vue
src/components/color-picker/index.js
src/components/color-picker/prefixMixin.js
src/components/color-picker/recommend-colors.vue
src/components/color-picker/saturation.vue
src/components/color-picker/utils.js
src/styles/components/color-picker.less
src/styles/mixins/input.less

Keyboard control for color picker

---

src/components/tabs/tabs.vue

Two problems that I found:
- fix too early visibility change (the animation was setting `visibility : hidden` to early, now waits for the transition to end
- trigger update on mounted (on mounted the elements where not being hidden, so tabbable content was still there and only hidden after first time tabs change)
Also made a small DRY of `getTabIndex` function

Tabs small fixes

---

src/components/select/select.vue

fixes https://github.com/iview/iview/issues/3656

Allow wider search pattern for filterable

---

examples/routers/select.vue
src/components/select/select.vue

Normalise v-click-outside-x for Select

---

src/components/date-picker/picker.vue
src/components/date-picker/util.js

Fix multidate parser value types, prevent undefined in focusedDate

---

src/components/select/select.vue
test/unit/specs/select.spec.js

Closes #3723
Fixes #3705, fixes #3725

Select improvements for edge cases

---

src/components/auto-complete/auto-complete.vue
src/components/select/select.vue

Change logic for hiding AutoComplete panel

---

examples/routers/menu.vue
src/components/menu/menu.vue
src/components/select/select.vue

修复当递归形式使用menu组件，并设置了accordion属性时，手风琴没有效果的bug

fixed bug of menu when use recursive components and set accordion

---

src/components/modal/mixins-scrollbar.js

fixed #3792 bug, when the modal component nested be used, child modal be close should not cause the scrollbar problem that user can scroll page.

fix bug #3792 Page scroll bar problem caused by Modal component

---

src/components/upload/ajax.js

fix: error msg
