iview/iview

- src/components/breadcrumb/breadcrumb.vue
使用 Breadcrumb 组件，如果在组件 `mounted` 时没有为 Breadcrumb 设置有效的 Breadcrumb-item 子组件（比如 Breadcrumb-item 是通过 Ajax 或者本地缓存异步加载过来的），则 Breadcrumb 对子组件的 分隔符(seperator) 初始化会失败，因为此时获得的 `this.$children` 长度为0。
* 解决方案：
> 在父组件（Breadcrumb）的 updated 事件里加入更新子组建设置的逻辑。
> [Fix] 使用 Breadcrumb 组件若初始化时没有设置子 Breadcrumb-item 则导航分隔符无法显示。

- src/components/table/cell.vue
在table的render中生成的组件，组件内部的代码无法通过this.$store来获取vuex对象
> 修正table render的自定义组件中无法获取this.$store的问题

- src/components/input/input.vue
Input component support `focus()` method
我有个使用场景，需要能通过编程方式，让 `Input` 组件获得焦点，用户就可以避免操作鼠标点击，从而提高效率，所以加了这个方法。
> [iView 2] input 支持 focus 方法

- src/components/transfer/transfer.vue
components/transfer name missing, will cause the following problems:
> fix components/transfer name missing

- src/components/input/input.vue
Thanks for `iView` to build the project of our team.
But today, when I want to add keyup and keydown event listener of `Input` components, I failed.
It's the case of my project:
I want to use keyup to set `shortcuts（快捷键）`  with Input components.I failed.
Now, I add the Event Listener to build my project, successfully.
Here is the test case, I was not commit it, but you can replace `examples/routers/input.vue` to see:
```vue
<template>
<div style="width: 100px;">
<Input v-model="value1" size="large" placeholder="large size" @on-enter="handleEnter" @on-keyup="handleKeyup" @on-keydown="handleKeydown" @on-keypress="handleKeypress"></Input>
<br>
<Input v-model="value2" placeholder="default size"></Input>
<br>
<Input v-model="value3" size="small" placeholder="small size"></Input>
<br>
<Input …
```
> fix: add keyup, keydown, keypress eventlistener of input component

- src/components/input-number/input-number.vue
Due to 0.07*100=7.000000000000001, 0.07 add -0.01 returns a wrong result.
> Fix a bug in input-number component

- src/styles/components/radio.less
When we have `<Button-group>` side by side with `<Radio-group>` the `vertical-align` does not match.
___
This change applies same `vertical-align` as in [button group](https://github.com/iview/iview/blob/v2.0.0/src/styles/mixins/butt
on.less#L56) and makes grouped radio buttons to have same vertical align.
> use vertical-align: middle; in radio group also

- src/components/date-picker/base/time-spinner.vue
- src/components/date-picker/panel/time.vue
- src/components/date-picker/picker.vue
- src/components/date-picker/picker/date-picker.js
- src/components/date-picker/picker/time-picker.js
- test/unit/specs/time-spinner.spec.js
This PR ads the possibility to choose `steps` in the formatting of the `hh:mm:ss` lists. 
For example: instead of lists of 60 items/minutes we can have ”5 in five minutes” or ”every 15 minutes”.
The sintax would be `:steps="[<hour steps>, <minute steps>, <second steps>]"`, with default to `1` so we have no breaking changes.
<Time-Picker :steps="[1, 15]" format="HH:mm"></Time-Picker>
**Demo:** https://jsfiddle.net/Sergio_fiddle/r6w7s68p/
This PR has 2 commits:
- code changes to add new feature
- unit tests for the normal behavior and the new behavior
If you want I can comment the code changes in the PR.
> Time-Picker new feature: allow steps in lists

- src/components/date-picker/util.js
- test/unit/specs/date-picker-utils.spec.js
Date utility functions `prevMonth` and `nextMonth` [change the source 
date before creating the return date](https://github.com/iview/iview/blob/v2.1.0/src/components/date-picker/util.js#L70-L74) when using `src.set[Date|Month|FullYear]()`. 
This change creates a copy of the date at entrance of function so we have a pure function.
Made also some code refactor and added specs for these functions.
> Date utils improvements and specs

- src/components/date-picker/base/time-spinner.vue
**Problem:**
When opening a `time-picker` with `steps` and `value` the initial scroll is broken. This is basically something I forgot to check when I implemented the feature, so here is the fix :)
**Example** (broken): https://jsfiddle.net/r6w7s68p/2/
**Example** (fixed): https://jsfiddle.net/r6w7s68p/3/
> Broken initial scroll in time-picker with steps 

- package.json
- src/components/date-picker/util.js
- src/index.js
**Problem:** IE 11 cannot parse date strings where month or date is only one character. 
This PR calls the date constructor with the separated string parts, only in case they fail to parse as dates.
Added also `Array.prototype.find` because [IE11 does not have it](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility).
fixes #1422
> Make date more IE friendly

- src/components/date-picker/base/date-table.vue
- test/unit/specs/date-picker.spec.js
- test/unit/util.js
- Added `cell.date` so we don’t need `.getDateOfCell()` anymore
- Passed `cell` directly in `@click="handleClick(cell)”` so we don’t need `const cell =
this.cells[parseInt(event.target.getAttribute('index’))];` anymore
___
- basic `type="datetimerange"` render
- basic `type="datetimerange"` pick 2 dates
- basic `type="datetimerange"` pick 2 dates > reset > pick 2 dates again 
The last test is related to #1223, #1301 & #1711
fixes #1223 
fixes #1301 
fixes #1734 
closes #1711
> Refactor cell click handler and add more date picker and date range picker tests

- src/components/select/select.vue
- test/unit/specs/select.spec.js
fixes #1687
fixes #622 
fixes #1112
fixes #1236
fixes #1211 
fixes #1765
> Use textContent to not escape html entities in Select options

- src/components/table/cell.vue
table 组件在渲染 形如 "&#x3C;a href=&#x22;test-url&#x22;&#x3E;test&#x3C;/a&#x3E;" 的数据时，会被渲染成为html元素，容易造成xss( known as: cross site script 可 )漏洞,出于安全方面考虑,该行为不宜作为组件默认选项(默认安全原则),故将默认选项改为模板渲染，并引入 html 的渲染模式。
相关描述：
[1] https://en.wikipedia.org/wiki/Cross-site_scripting
[2] https://cn.vuejs.org/v2/api/#v-html
> impove table render logic,fix xss.

- src/components/select/select.vue
- src/components/select/utils.js
- test/unit/specs/select.spec.js
Since large array of options calls `.on('append'` and `.on('remove'` multiple times this PR makes them be called only 1 time.
fixes #873
> Optimize append and remove options

- src/components/form/form.vue
If you want to prevent submit, use this instead:
```
<Form @submit.native.prevent>
```
It break the browser default behavior in #968 which makes more troubles.
> Rollback #968

- src/components/date-picker/panel/date-range.vue
- src/components/date-picker/panel/date.vue
- src/components/date-picker/panel/time-range.vue
- src/components/date-picker/panel/time.vue
- src/components/date-picker/picker.vue
Datepicker opens on input focus with click or Tab navigation.
Datepicker closes when we click outside it but doesn't close when we tab-navigate away.
fixes #1930
> make picker close on blur

- src/components/avatar/avatar.vue
There are chances that when there is this.$slots.default there is no this.$refs.children.
> Patch fix on Avatar component

- src/components/table/table.vue
table里的td再创建个table会报以下错误，已测试过
>[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'width' of undefined"
> 修复table里嵌套table报 Cannot read property 'width' of undefined"的错误

- src/components/date-picker/picker.vue
When we compile code with Nuxt `Date` objects gets converted to `.ISOString()`. So if we have a example with `year: new Date('1977')` server side, this gets converted to `year: '1976-12-31T23:00:00.000Z'` in client side, and breaks validation ([jsFiddle](https://jsfiddle.net/Sergio_fiddle/grbzcx80/)).
If we force a date re-check the Date will be parsed as Object by DatePicker and thus pass validating.
fixes https://github.com/iview/iview/issues/1971
> force string dates parse

- src/components/date-picker/base/time-spinner.vue
Remove `Array.find` code because IE11 doesn't like it and Babel doesn't polyfill it. We could also use the `es2015-ie` babel plugin but the refactor is actually more semantic correct.
related https://github.com/iview/iview/issues/1937
> remove Array.find to make IE11 happy

- src/components/date-picker/picker.vue
When we insert invalid input in date-picker `Input` iview `throw` error. This change makes the input value be empty.
fixes #1872, fixes #1995
> Return empty string if the date input doesn't parse

- src/components/form/form-item.vue
为`FormItem`设置`:error`，以动态将其标记为验证错误；但是此后，即使内容修改为正确的值，再次执行验证时，`FormItem`的边框仍然是红色的，因为`validateState`的值还是`error`
> 修正`FormItem`使用`:error`动态设置错误信息后，`validateState`的值`error`永远无法清空的BUG

- src/styles/components/color-picker.less
It seems `cursor:hand` only worked in IE 5.5 and below.
In this place, the cursor style has already defined by its parent div, so remove it.
> Remove unused and typo cursor style in ColorPicker

- src/components/input-number/input-number.vue
Add `readonly` prop & functionality to Input Number component.
Syntax: `<input-number v-model="number" readonly></input-number>`
> Add readonly prop to input-number

- src/components/input-number/input-number.vue
Text input updates `v-model` [on every input](https://github.com/iview/iview/blob/v2.4.0/src/components/input/input.vue#L29). 
This change makes `input-number` behave same way.
> fire change on "input" event

- src/components/date-picker/panel/date-panel-label.vue
- src/components/date-picker/panel/date-range.vue
- src/components/date-picker/panel/date.vue
- src/components/date-picker/panel/time-range.vue
- src/components/date-picker/util.js
- src/locale/lang/de-DE.js
- src/locale/lang/en-US.js
- src/locale/lang/es-ES.js
- src/locale/lang/fr-FR.js
- src/locale/lang/id-ID.js
- src/locale/lang/ja-JP.js
- src/locale/lang/ko-KR.js
- src/locale/lang/pt-BR.js
- src/locale/lang/pt-PT.js
- src/locale/lang/ru-RU.js
- src/locale/lang/sv-SE.js
- src/locale/lang/tr-TR.js
- src/locale/lang/vi-VN.js
- src/locale/lang/zh-CN.js
- src/locale/lang/zh-TW.js
This changes how Date picker label is displayed.
With this change the text for `month year` comes from JavaScript [Date.prototype.toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) combined with the locale file `i.datepicker.datePanelLabel`. 
What we can configure is the format following this pattern:
>**yyyy** - 4 digit year
**m** - month, numeric, 1 - 12
**m** - month, numeric, 01 - 12
**mmm** - month, 3 letters, as in `toLocaleDateString`
**Mmm** - month, 3 letters, capitalize the return from `toLocaleDateString`
**mmmm** - month, full name, as in `toLocaleDateString`
**Mmmm** - month, full name, capitalize the return from `toLocaleDateString`
The `[...]` indicates the month or year field that will be used as target …
> use date.toLocaleDateString to format year/month

- src/components/tree/node.vue
- src/components/tree/tree.vue
- src/styles/components/tree.less
Refactor Tree component code to fix async loading and bugs.
I removed the findComponentDownwards logic so we can do `v-if` and not render parts of Tree that are not expanded. This way we have a state tree complete even if some nodes are not rendered in DOM.
fixes #1993
fixes #1943
fixes #1897
fixes #1776
fixes #791 
fixes #1717
fixes #1693 
fixes #1597
closes #1767
related #587 (with this PR the `indeterminate` state is part of the Tree `data`, but we have no event for `indeterminate`. Not sure it is needed)
> Refactor tree

- src/components/scroll/scroll.vue
This ads a new prop in Scroll where callback can be fired by distance to edge. If distance passed is negative, it will fire before reaching edge.
Possible values:
(as discussed in #2137)
- **Number**: in this case will use **same value** to both `top` and `bottom` values
- **Array**: in this case will be used as `[top value, bottom value`
fixes #2137
> add distance-to-edge property

- src/index.js
- src/locale/locales.js
Export `locale` objects so we can use iView directly on the browser easier.
This changes allows to use locale on the browser directly:
```
const lang = 'sv-SE';
const locale = iview.locales[lang];
Vue.use(iview, {
locale: locale
});
```
Example: http://jsfiddle.net/Sergio_fiddle/174cbLax/
Related to Stackoverflow question: https://stackoverflow.com/q/46989680/2256325
> export locale objects

- src/components/form/form.vue
- src/components/input-number/input-number.vue
- src/components/input/input.vue
- src/components/page/options.vue
- src/components/page/page.vue
- src/components/select/select.vue
This allows the user to control the `autocomplete` and `spellcheck` attribute in `<Input>` and `<Form>` component. 
This PR also forces `off` in input elements that are not part of forms, and are used internally by iview.
Related: https://github.com/iview/iview/issues/2118
> normalize autocomplete and spellcheck

- test/unit/specs/date-picker.spec.js
Make input send change event before `picker` is deployed
fixes #2215
> add test for #2215

- src/components/date-picker/util.js
Avoid using `.includes()` to make IE happy and avoid adding Polyfill
fixes #2330
> Don't use includes to make IE happy and avoid Polyfill

- src/components/date-picker/panel/date-range.vue
Apparently Chromium has a bug that cannot set values without waiting a bit...
fixes https://github.com/iview/iview/issues/2122
> Patch Chromium bug

- src/components/tabs/tabs.vue
This PR fixes a issue when looking up in DOM tree we end up checking `html` node's `style` attribute.
Example of the problem: https://jsfiddle.net/be0Lukf6/
More description in Gitter ([in Chinese so I didn't get all of it](https://gitter.im/iview/iview?at=5a0946da71ad3f8736d91b87) 😛 )
> don't check past document.body when moving up DOM tree 

- src/components/input-number/input-number.vue
fix checking when temp number is invalid  and should be rechecked in `change` event
fixes #2418
> fix checking when temp number is invalid 

- src/components/input/input.vue
Why do you need a validator on `type` value? Is it ok to remove this validator?
> Support more types on <i-input>

- src/components/scroll/scroll.vue
I noticed that when a component is destroyed and it is scrolling we get a error because `this.$refs.scrollContainer` is not in DOM  anymore. This fixes that.
> check for element before using it

- src/components/color-picker/color-picker.vue
Add a property to decide whether saturation panel should show. Fix issue #2672.
> Add saturation property

- examples/routers/slider.vue
- src/components/slider/slider.vue
This is a Slider refactor. Main changes:
- removed `single`, `first`, `second` logic. Now we have just `min` and `max`. This makes easier to add vertical slider later.
- internal value is always Array, and will export Number or Array as before depending on `this.range`.
- added touch (fixes #2367)
- added more code in dev example page
> Refactor slider

- src/components/table/mixin.js
If a table has heigth and last column is auto width
``` js
let width = ''
// is_last_column, true && top_always_true && height_set_by_user, true
if ( this.columns.length === index + 1 && top && this.$parent.bodyHeight !== 0) {
// width will be 0 + this.$parent.scrollBarWidth === this.$parent.scrollBarWidth
// so last column will be 10~20px(the width of scrollBar)
}
```
there is an example with iview@2.8.0
- [gist](https://gist.github.com/anonymous/e04e86c9e99d4d1e97bf327769acd345)
- [demo on jsbin](http://jsbin.com/soqogagiqu)
> fix last column resize bug when no data

- src/components/dropdown/dropdown.vue
When a dropdown is in `custom` trigger mode we have no feedback if there is a click outside the dropdown. I think this is useful for the manual control of the dropdown visibility.
Example: https://jsfiddle.net/mdc1792o/3/
> New feature: add "clickoutside" event emitter to dropdown

- .babelrc
- package-lock.json
- package.json
- yarn.lock
Stay up to date, by using the env preset.
https://babeljs.io/docs/plugins/preset-es2015/
https://babeljs.io/docs/plugins/preset-env/
`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!`
> Upgrade: babel-preset-es2015 to babel-preset-env

- package-lock.json
- package.json
- yarn.lock
> The babel npm package no longer exists. Instead, Babel has been split into multiple packages:
> 
> babel-cli, which contains the babel command line interface
> 
> babel-core, which contains the Node API and require hook
> 
> babel-polyfill, which when required, sets you up with a full ES2015-ish environment
https://babeljs.io/docs/usage/cli/
`npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers`
> Upgrade: babel to babel-cli

- .babelrc
- package-lock.json
- package.json
- yarn.lock
As described in WeChat.
This implements the configuration from the PRN project and gives specific support for the listed browsers via babel transpilation and pollyfilling.
It also gives the end user an unequivocal list of browsers that this project supports.
It would be good to include this list in the web site documentation for easy reference.
Refs:
https://github.com/babel/babel/tree/master/packages/babel-preset-env
https://github.com/ai/browserslist
http://browserl.ist/
https://kangax.github.io/compat-table/es6/
> Enhancement: Implement browserlist, specifically babel orientated.

- src/components/select/select.vue
Fix #982 issue.Make Null acceptable for Select tag（让Select标签可以接收null值）
Sometimes the Select tag in From defaults null, it won't reset empty where trigger 'resetFields' method.The pull request attempt to solve the issue.
有的时候Form中Select控件的默认值是null，这个时候调用resetFields会导致Select不会清空。本次提交为了解决这个问题。
> Fix #982 issue.Make Null acceptable for Select tag（让Select标签可以接收null值）

- src/components/avatar/avatar.vue
Now the Avatar childrenOffsetWidth can be re-measured while slot data being changed.
#3033 #3028
> [Bug Fix] Avatar's slot content not being center after update

- examples/main.js
(Polyfill) This is required when developing with older browser i.e. IE11.
The locale change is because it is really difficult for non-chinese reading/speaking developers to understand what they are seeing on the page when developing this project.
> Use babel-polyfill for testing examples

- src/styles/common/base.less
In https://github.com/iview/iview/blob/v2.9.2/src/styles/common/base.less#L34-L37 iview resets the global style for `<li>` tags. This is being applied to the global CSS of projects using iview. This CSS is already being used in specific components that need it.
This should not be global, if we find some use case that needs this we can patch that specific component or add a class in this reset to make it scoped and not global.
> Remove global list-style reset

- src/components/select/prefixCls.js
Composed string that can be used within iview and by users of the library.
> Use constant for CSS prefixes

- src/components/form/formItemName.js
- src/components/form/formName.js
- src/components/select/dropdownName.js
- src/components/select/optionGroupName.js
- src/components/select/optionName.js
- src/components/select/selectName.js
While using Pascal Case for names will not be breaking within iview itself, there is the possibility that users are searching these names in there own code.
https://vuejs.org/v2/style-guide/#Single-file-component-filename-casing-strongly-recommended
Further reasons for splitting these out are that if you begin to use https://github.com/vuejs/eslint-plugin-vue for the project then eslint will automatically correct these to Pascal Case. If you choose to continue using a small `i` for component names then eslint will not touch these files. External users can also reference these constants in their code without the fear of any future changes in component names. This would ideally be done for all components in iview in the future, this PR just deals with the rework of the select component and …
> Use constant component names in Pascal Case as per vue standards

- package-lock.json
- package.json
- yarn.lock
https://www.npmjs.com/package/v-click-outside-x
This is required for event capturing which is not supported in the current iview directive.
It also supports `pointerevents` and is far more economical about adding event listeners to document.
Eventually this can replace the iview directive in all other components that use it.
> Add v-click-outside-x directive

- src/components/date-picker/panel/Date/date.vue
- src/components/date-picker/picker.vue
When in multiple mode picking, the date used for the days table was always the first in the dates array, this changes to the last picked date instead.
> Use last picked date in multiple mode for panel date

- src/styles/components/select.less
Loos like the groups list was using the global CSS we removed in https://github.com/iview/iview/pull/3061
> correct list-style of groups

- build/webpack.dist.dev.config.js
> Fix: dist.dev need to use production sourcemaps not development

- src/components/input/input.vue
Fix clearable and icon conflict while `clearable` and `icon` options are used. `clearable` should show when this option is enable and the currentValue is not empty, otherwise the `icon` will never be shown.
`npm test` passed.
> Fix a confliction in Input component

- src/components/slider/slider.vue
表单布局中包含slider时，input 样式无法统一。
或者考虑 允许 `showInput` 的值为 `String`。控制input的size。
> add props input-size

- examples/routers/input-number.vue
- src/components/input-number/input-number.vue
在on-focus事件中增加返回值event，使用组件时即可 `event.target.select()` 选中已有值。
在safari浏览器中，需要增加设置mouseup事件preventDefault才能实现。
在chrome浏览器中，可以不需要设置mouseup事件preventDefault。
其余浏览器未测试。
> 实现InputNumber获取焦点时选中已有值，增加on-focus的返回值event。

- src/components/date-picker/panel/Date/date-range.vue
- src/components/date-picker/panel/Date/date.vue
- src/components/date-picker/panel/Time/time-range.vue
- src/components/date-picker/panel/Time/time.vue
- src/components/date-picker/panel/panel-mixin.js
- src/components/date-picker/picker.vue
(New Feature)
When we use the `@on-change` event in `DatePicker` we get only a new string `dddd-mm-yy hh:mm:ss` in the functions 1st argument. This change adds a new argument so we can know what was changed, if the `date` or the `time` in case of `datetime` picker. 
Test case:
```
<template>
<div style="width: 500px;margin: 100px;">
<date-picker type="date" @on-change="onChange"></date-picker>
</div>
</template>
<script>
export default {
methods: {
onChange(...args){
console.log(...args);
}
}
}
</script>
```
> Expose changed date component

- examples/routers/table.vue
- src/components/table/table.vue
计算宽度的时候减去一个像素，解决table样式border-collapse: collapse;时，总会有滚动条
> fixed table

- src/components/radio/radio-group.vue
使用:value绑定的时候，RadioGroup并不能正常切换。
> 修复RadioGroup只能在使用v-model绑定的情况下才能正常使用的bug。

- examples/routers/color-picker.vue
- src/components/color-picker/color-picker.vue
(New feature)
This change adds to color-picker a similar event like date-picker already has:
> Add open change event to color picker

- src/locale/lang/cs-CZ.js
I added the translation for the Czech language. The only problem is that Czech has three plural forms, which is not supported in this version of the translation. Maybe it would be better to add some pluralization plugin (e.g. https://github.com/scottrippey/Smart-Plurals) because this is not a case for Czech only but for more languages.
Example of plural forms:
1 item = 1 **polozka**
2-4 items = 2-4 **polozky**
5+ items = 5+ **polozek**
> Add support for Czech

- src/components/menu/menu.vue
修复 on-open-change事件返回的当前展开的 Submenu 的 name 值数组不正确的问题
> update menu.vue updateOpenKeys methods

- src/components/date-picker/panel/Date/date-range.vue
- src/styles/components/date-picker.less
Correct panel width when showing week numbers.
Demo: https://jsfiddle.net/4d2Ljf64/
Image of the problem:
> Correct time layout when showing week numbers

- examples/routers/tabs.vue
- src/components/tabs/tabs.vue
This PR corrects the two problems we discussed before:
https://jsfiddle.net/oygz6suu/1/
1. the children css set display:none when change pane;
2. the event @on-click does not trigger when using keyboard space.
> Correct logic for selecting by keyboard

- src/components/tabs/tabs.vue
Using `display: none;` created some unexpected problems and actually `visibility` does the same effect of preventing elements to be focusable, which is better than the first solution. 
I should have came up with this version from the beginning.
> Use visibility instead of display

- src/components/select/option.vue
- src/components/select/select.vue
Use `option.label` first and only `textContent` as a fallback
> Use label first if available

- src/components/tabs/tabs.vue
This PR is a fix for #3732. The possibility to do TAB navigation added new challenges and we need to have control of the `focused` element. Since this is a breaking change we could have a prop for it called `:capture-focus` that defaults to `false` to keep the old behaviour. We can discuss later how the behaviour should be in 3.0.
> Fix 3732 - add prop for capturing focus

- src/components/select/option.vue
- src/components/select/select.vue
Be more hard on the reset: Fixes #3746
Correct event propagation on transfer: Fixes #370,  Fixes #3695 
Detect `touchend` so touch devices can also select options: Fixes #3741
> Select fixes

- src/components/date-picker/panel/Date/date-range.vue
- src/components/date-picker/picker.vue
- Use first day of month to avoid getting higher numbers than the month has. Fixes #3773
- Focus only if component has input. Fixes #3769
> Datepicker patches
